import Feed from "@components/Feed/Feed";
import "../styles/hreoSection.css";
export const metadata = {
  title: "Blog With AI Application Home Page.",
  description: "Generated by create next app",
};
export default function Home() {
  return (
    <section className="text-center">
      <div className="flex flex-col items-center">
        <h2 className="text-4xl font-bold py-4">Discover & Share</h2>
        <h2 className="text-3xl h-ai font-bold my-3">AI-Powered Prompts</h2>
        <p className="text-xl font-semibold px-4 ">
          Promptopia is an open-source AI model and programming tool for modern
          world to discove,create and share creative prompts.
        </p>
      </div>
      <Feed />
    </section>
  );
}
